set(TARGET llama-gemma-in-memory)
add_executable(${TARGET} in-memory.cpp)
target_link_libraries(${TARGET} PRIVATE llama llama-common ggml)
target_compile_features(${TARGET} PRIVATE cxx_std_17)
if (LLAMA_TOOLS_INSTALL)
    install(TARGETS ${TARGET} RUNTIME)
endif()

if (LLAMA_BUILD_SERVER)
    foreach(TARGET llama-gemma-zero-copy-server llama-zero-copy-server)
        add_executable(${TARGET} service.cpp)
        target_include_directories(${TARGET} PRIVATE ../server ${CMAKE_SOURCE_DIR})
        target_link_libraries(${TARGET} PRIVATE llama llama-common llama-server-impl ggml ${CMAKE_THREAD_LIBS_INIT})
        target_compile_features(${TARGET} PRIVATE cxx_std_17)
        if (LLAMA_TOOLS_INSTALL)
            install(TARGETS ${TARGET} RUNTIME)
        endif()
    endforeach()
endif()
