if (NOT DEFINED TEST_EXE OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "Missing Q6 test parameters")
endif()
set(off "${OUTPUT_DIR}/q6-pair-off.bin")
set(on "${OUTPUT_DIR}/q6-pair-on.bin")
execute_process(COMMAND "${TEST_EXE}" off "${off}" RESULT_VARIABLE off_result TIMEOUT 30)
execute_process(COMMAND "${TEST_EXE}" on "${on}" RESULT_VARIABLE on_result TIMEOUT 30)
if (NOT off_result EQUAL 0 OR NOT on_result EQUAL 0)
    message(FATAL_ERROR "Q6 pair graph execution failed: off=${off_result}, on=${on_result}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${off}" "${on}" RESULT_VARIABLE different)
if (NOT different EQUAL 0)
    message(FATAL_ERROR "Q6 pair changed output bytes")
endif()
file(SHA256 "${off}" off_hash)
file(SHA256 "${on}" on_hash)
message(STATUS "Q6 pair output SHA256: off=${off_hash} on=${on_hash}")
file(REMOVE "${off}" "${on}")
message(STATUS "Q6 pair: all graph outputs bit-identical with opt-in off/on")
